FROM node:18-alpine

WORKDIR /app

# Copiar arquivos de dependências
COPY package*.json ./
COPY yarn.lock ./

# Instalar dependências usando Yarn
RUN yarn install --frozen-lockfile

# Copiar resto do código
COPY . .

ENV NEXT_PUBLIC_API_URL=http://localhost:8080

# Build com Yarn
RUN yarn build

EXPOSE 3000

# Iniciar com Yarn
CMD ["yarn", "start"]