version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-fila-banco
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fila_banco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fila-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-fila-banco
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - fila-network

  app:
    build: .
    container_name: app-fila-banco
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fila_banco
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - fila-network

networks:
  fila-network:
    driver: bridge

volumes:
  mysql_data: